version: "3"

services:
  postgres:
    image: postgres:13-alpine
    container_name: pbd_db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
